[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm.git"
refreshPeriod = "168h"

[".local/share/zinit/zinit.git"]
type = "git-repo"
url = "https://github.com/zdharma-continuum/zinit.git"
refreshPeriod = "168h"

[".local/share/nvim/lazy/lazy.nvim"]
type = "git-repo"
url = "https://github.com/folke/lazy.nvim.git"
refreshPeriod = "168h"
[".local/share/nvim/lazy/lazy.nvim".clone]
args = ["--filter=blob:none", "--branch=main"]
