format = """
$os \
$directory \
$git_branch\
$git_commit\
$git_status\
$git_metrics \
$nodejs\
$python\
$rust\
$golang\
$nix_shell \
$time
$character"""

[os]
disabled = false
style = "fg:#c0caf5"
format = "[$symbol]($style)"

[directory]
style = "fg:#769ff0"
format = "[📁 $path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:#bb9af7"
format = "[$symbol $branch(:$remote_branch)]($style)"

[git_commit]
style = "fg:#bb9af7"
format = "[ $hash$tag]($style)"
commit_hash_length = 7
tag_disabled = false
tag_symbol = " 🏷 "

[git_status]
style = "fg:#bb9af7"
format = "[ $ahead_behind$conflicted$stashed$staged$modified$renamed$deleted$untracked]($style)"
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇡${ahead_count}⇣${behind_count} "
conflicted = "=${count} "
stashed = "*${count} "
staged = "+${count} "
modified = "!${count} "
renamed = "»${count} "
deleted = "✘${count} "
untracked = "?${count} "

[git_metrics]
disabled = false
format = "([+$added]($added_style) )([-$deleted]($deleted_style) )"
added_style = "fg:#9ece6a"
deleted_style = "fg:#f7768e"

[nodejs]
symbol = "📦"
style = "fg:#a0a9cb"
format = "[$symbol $version]($style) "

[python]
symbol = "🐍"
style = "fg:#a0a9cb"
format = "[$symbol $version]($style) "

[rust]
symbol = "🦀"
style = "fg:#a0a9cb"
format = "[$symbol $version]($style) "

[golang]
symbol = "🐹"
style = "fg:#a0a9cb"
format = "[$symbol $version]($style) "

[nix_shell]
symbol = "❄️"
style = "fg:#7dcfff"
format = "[$symbol $state]($style) "

[time]
disabled = false
time_format = "%R"
style = "fg:#565f89"
format = "[🕐 $time]($style)"
