name: Validate Dotfiles

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux x86_64
          - os: macos-13
            name: macOS Intel
          - os: macos-latest
            name: macOS Apple Silicon
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: "experimental-features = nix-command flakes"
      - run: nix flake check --no-build
